version: "3.8"

services:
  mysqldb:
    image: mysql
    container_name: mysqldb
    environment:
      - mysql_INITDB_ROOT_USERNAME=root
      - mysql_INITDB_ROOT_PASSWORD=pass12345
    volumes:
      - mysqldb-data:/data/db
    networks:
      - mysqldb_network
    ports:
      - 27017:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mysql 10.10.10.60:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  grafana:
    image: grafana
    container_name: grafana
    environment:
      - ME_CONFIG_mysqlDB_SERVER=mysqldb
      - ME_CONFIG_mysqlDB_ENABLE_ADMIN=true
      - ME_CONFIG_mysqlDB_ADMINUSERNAME=root
      - ME_CONFIG_mysqlDB_ADMINPASSWORD=pass12345
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    depends_on:
      - mysqldb
    networks:
      - mysqldb_network
    ports:
      - 8081:8081
    healthcheck:
      test:  wget --quiet --tries=3 --spider http://admin:admin123@10.10.10.60:8081 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

volumes:
  mysqldb-data:
    name: mysqldb-data

networks:
  mysqldb_network:
    name: mysqldb_network